# Generated by Django 2.0 on 2018-11-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=150)),
                ('tipo', models.CharField(max_length=150)),
                ('motivo', models.CharField(max_length=150)),
                ('voucher', models.FileField(max_length=250, null=True, upload_to='storage/images/')),
            ],
            options={
                'db_table': 'solicitudes',
            },
        ),
    ]
